Update patch set 2
Patch Set 2: Code-Review-1

breaks build 
ERROR: /packages/apps/Settings/src/com/android/settings/deviceinfo/SimStatus.java:411.38: KEY_HIDE_SIGNAL_STRENGTH_IN_SIM_STATUS_BOOL cannot be resolved or is not a field

Patch-set: 2